<?php

/**
 * Implements hook_add_to_vejviser (@see bibdk_vejviser.module)
 * */
function bibdk_favourite_add_to_vejviser($branch) {
  $ret = drupal_get_form('bibdk_favourite_select_form', $branch);
  return drupal_render($ret);
}

/** \brief button to add a library to favourites
 * @param type $form
 * @param type $form_state
 * @return string
 */
function bibdk_favourite_select_form($form, $form_state) {
  $form['favourite_button'] = array(
    '#type' => 'submit',
    '#value' => t('Tilføj til favoritbiblioteker'),
    '#ajax' => array(
      'callback' => 'bibdk_favourite_ajax_add_favourite',
    ),
  );
  return $form;
}

/**
 * Ajax callback function
 * add favourite to session
 * set a message
 * */
function bibdk_favourite_ajax_add_favourite($form, $form_state) {
  $branch = $form_state['build_info']['args'][0];
  $result = bibdk_favourite_add_favourite_to_session($branch);

  drupal_set_message($result);

  // insert a drupal messagebox on branch (class="message_$branchId")
  $bibname = $_SESSION['bibdk_favourites'][$branch->branchId]->branchName;
  $text = t('@bibname has been added to your favourite libraries', array('@bibname' => $bibname));
  $commands = array();
  $selector = '.messages_' . $branch->branchId;
  drupal_set_message($text);
  $commands[] = ajax_command_replace($selector, theme('status_messages'));

  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Add favourite library to sesssion
 * */
function bibdk_favourite_add_favourite_to_session($branch) {
  if (!isset($_SESSION)) {
    drupal_session_initialize();
    $_SESSION['bibdk_favourites'] = array();
  }

  // @TODO; save on webservice
  if (!isset($_SESSION['bibdk_favourites'][$branch->branchId])) {
    $_SESSION['bibdk_favourites'][$branch->branchId] = serialize($branch);
    //try to save
    $response = _bibdk_favourite_save_on_webservice($branch);
  }
}

/** \brief delete user on webservice
 *
 * @global $user
 * @param  $branchId
 * @return FALSE if user is not logged in or is not ding_provider_user
 * or something goes wrong. TRUE if all went well
 */
function _bibdk_favourite_delete_on_webservice($branchId) {
  global $user;
  if ($user->uid) {
    if (ding_user_is_provider_user($user)) {
      try {
        $creds = ding_user_get_creds($user);
      } catch (Exception $e) {
        // do nothing ding user handles this case
      }
      // check if user is logged in and if so if user is provider user
      $response = bibdk_provider_delete_favourite($creds['name'], $branchId);

      return $response;
    }
    // user is not provider user
    // @TODO; return something else
    return FALSE;
  }
  // user is not logged in
  // @TODO; return something else
  return FALSE;
}

function bibdk_favourite_form_profile2_form_alter(&$form, &$form_state) {
  // add a submit function
  $form['#submit'][] = 'bibdk_favourite_profile2_submit';
}

/** \brief submit handler for profile2 form
 * clear messages and set a proper one
 *  * @param type $form
 * @param type $form_state
 */
function bibdk_favourite_profile2_submit($form, $form_state) {
  // clear message stack
  drupal_get_messages();
  // @TODO set a proper message;
  drupal_set_message('page_refreshed');
}

/** \brief save user on webservice
 *
 * @global $user
 * @param  $branch
 * @return FALSE if user is not logged in or is not ding_provider_user
 * or something goes wrong. TRUE if all went well
 */
function _bibdk_favourite_save_on_webservice($branch) {
  // check if user is logged in and if so if user is provider user
  global $user;
  if ($user->uid) {
    if (ding_user_is_provider_user($user)) {
      try {
        $creds = ding_user_get_creds($user);
      } catch (Exception $e) {
        // do nothing ding user handles this case
      }
      // check if user is logged in and if so if user is provider user
      $response = bibdk_provider_add_favourite($creds['name'], $branch->branchId);
      return $response;
    }
    // user is not provider user
    // @TODO; return something else
    return 'FALSE';
  }
  // user is not logged in
  // @TODO; return something else
  return 'FALSE';
}

/** \ Delete favourite from SESSION and on webservice
 *
 * @param type $branchId
 * @return boolean
 */
function bibdk_favourite_delete_favourite_from_session($branchId) {
  $ret = TRUE;

  // check if we should delete on webservice
  global $user;
  if (ding_user_is_provider_user($user)) {
    $ret = _bibdk_favourite_delete_on_webservice($branchId);
  }

  if ( $ret && isset($_SESSION['bibdk_favourites'][$branchId] ) ) {
    unset($_SESSION['bibdk_favourites'][$branchId]);
  }

  return $ret;
}

/**
 * Implememts hook_user_profile_tabs (@see ding_user.module)
 * */
function bibdk_favourite_user_profile2_tabs() {
  $ret->label = t('favourites');
  //$ret->form = 'bibdk_favourite_form_view_items_from_session';
  $ret->form = bibdk_favourite_get_forms();
  //'bibdk_favourite_get_forms';
  $ret->type = 'bibdk_favourite_list';

  return $ret;
}

function _bibdk_favourite_set_agencies() {
  $agencies = array();

  if (empty($agencies)) {
    // try to get from webservice
    $agencies = _bibdk_favourite_get_from_webservice();
    if (!empty($agencies)) {
      // add agencies to session
      foreach ($agencies as $branch) {
        bibdk_favourite_add_favourite_to_session($branch);
      }
    }
  }
  //return $agencies;
}

/**
 * Implements hook_user_login
 */
function bibdk_favourite_user_login(&$edit, $account) {
  // TODO check if favourites are set in $_SESSION  if so :
  // ask user if he wants to save the favourites
}

function bibdk_favourite_get_forms() {
  $agencies = isset($_SESSION['bibdk_favourites']) ? $_SESSION['bibdk_favourites'] : NULL;
  if (empty($agencies)) {
    _bibdk_favourite_set_agencies();
  }
  $agencies = isset($_SESSION['bibdk_favourites']) ? $_SESSION['bibdk_favourites'] : NULL;

  if (!empty($agencies)) {
    foreach ($agencies as $id => $branch) {
      $form_ids[] = 'bibdk_favourite_' . $id;
    }
    return $form_ids;
  }
}

/**
 * the form to be displayed on profile tab
 * */
function bibdk_favourite_form_view_items_from_session($form, &$form_state, $branch) {
  $branch = unserialize($branch);
  $form['#title'] = $branch->branchName;

  $form[$branch->branchId]['#prefix'] = '<article class="library"> <div class="favourite_' . $branch->branchId . '">';
  $form[$branch->branchId]['#suffix'] = '</div></article>';

  $actions = bibdk_favourite_get_action_links($branch);
  
  $moreinfo = theme('bibdk_favourite_more_info', array('branch' => $branch,
    'openingHours' => theme('bibdk_favourite_opening_hours', array('branch' => $branch,)),
    'tools' => theme('bibdk_favourite_tools', array('branch' => $branch)),
    'address' => theme('bibdk_favourite_address', array('branch' => $branch)),
    'contact' => theme('bibdk_favourite_contact', array('branch' => $branch)),
      ));

  $form[$branch->branchId]['library']['#markup'] =
      theme('bibdk_favourite_library', array('branchName' => $branch->branchName, 'actions' => $actions, 'moreinfo' => $moreinfo));      

  return $form;
}

/*
 * Implements hook_forms.
 * drupal_get_form uses this hook if given formid is not found
 *
 * add a form for each of a users favourite agencies.
 */

function bibdk_favourite_forms($form_id) {
  // is this a bibdk_favourite form ?
  if (strpos($form_id, 'bibdk_favourite_') === 0) {
    $agencies = isset($_SESSION['bibdk_favourites']) ? $_SESSION['bibdk_favourites'] : NULL;
    if (empty($agencies)) {
      _bibdk_favourite_set_agencies();
    }

    $agencies = isset($_SESSION['bibdk_favourites']) ? $_SESSION['bibdk_favourites'] : NULL;
    foreach ($agencies as $id => $branch) {
      $forms['bibdk_favourite_' . $id] = array(
        'callback' => 'bibdk_favourite_form_view_items_from_session',
        'callback arguments' => array($branch),
      );
      $forms['bibdk_favourite_actions_' . $id] = array(
        'callback' => 'bibdk_favourite_form_elements',
        'callback arguments' => array($branch),
      );
    }
    return $forms;
  }
}

function theme_bibdk_favourite_contact($variables) {
  $branch = $variables['branch'];
  $contact_array = $branch->getContact();
  $output = '';
  if (!empty($contact_array)) {
    foreach ($contact_array as $key => $value) {
      $output .= $key . ' : ' . $value . '<br/>';
    }
  }
  return $output;
}

function theme_bibdk_favourite_opening_hours($variables) {
  $branch = $variables['branch'];
  global $language;
  $lang = $language->language;
  $render_array = array('#markup' => $branch->getOpeningHours($lang));
  if (empty($render_array)) {
    return;
  }
  return drupal_render($render_array);
}

/**
 * Render user fields;
 */
function bibdk_favourite_user_form_fields($form, &$form_state, $branchid) {
  $form['#branchid'] = array(
    '#type' => 'hidden',
    '#value' => $branchid,
  );

  if (!isset($_SESSION['bibdk_favourites'])) {
    $agencies = _bibdk_favourite_get_from_webservice();
    foreach ($agencies as $key => $value) {
      $_SESSION['bibdk_favourites'][$key] = serialize($value);
    }
  }


  if (isset($_SESSION['bibdk_favourites'][$branchid])) {
    $fields = bibdk_favourite_get_agency_fields($branchid);

    //dpm($_SESSION['bibdk_favourites'][$branchid]);
    $agency = unserialize($_SESSION['bibdk_favourites'][$branchid]);
    $agency->userParameters = $fields;
    $_SESSION['bibdk_favourites'][$branchid] = serialize($agency);
  }

  if (empty($fields) || !is_object($agency)) {
    // do something
    return;
  }

  foreach ($fields->getUserParameters() as $userParameter) {
    $value = isset($agency->userdata[$userParameter['type']]) ? $agency->userdata[$userParameter['type']] : NULL;
    $type = $userParameter['type'];
    $form[$type] = array(
      '#type' => isset($userParameter['field_type']) ? $userParameter['field_type'] : 'textfield',
      '#title' => $userParameter['field_name'],
      '#description' => isset($userParameter['field_description']) ? $userParameter['field_description'] : NULL,
      '#required' => $userParameter['required'],
      '#default_value' => isset($value) ? $value : "",
    );
  }

  $form['#submit'][] = 'bibdk_favourite_set_userdata';
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('SaveHest'),
  );
  return $form;
}

function bibdk_favourite_set_userdata($form, $form_state) {
  $userdata = array();
  $valid_fields = array('cpr', 'pincode', 'userName', 'userAddress', 'userMail', 'userTelephone');
  foreach ($form_state['values'] as $key => $value) {
    if (in_array($key, $valid_fields)) {
      if (!empty($value)) {
        $userdata[$key] = $value;
      }
    }
  }
  $agencyid = $form['#branchid']['#value'];
  bibdk_favourite_save_userdata($agencyid, $userdata);
  // clear session
  if (isset($_SESSION['bibdk_favourites'])) {
    unset($_SESSION['bibdk_favourites']);
  }
}

function bibdk_favourite_save_userdata($agencyid, array $userdata) {
  global $user;
  if (!ding_user_is_provider_user($user)) {
    return;
  }
  try {
    $creds = ding_user_get_creds($user);
  } catch (Exception $e) {
    // do nothing
  }
  $data = serialize($userdata);
  $response = bibdk_provider_user_save_favourite_data($creds['name'], $agencyid, $data);

  if ($response !== FALSE) {
    drupal_set_message(t('user_changes_saved'));
  }
  else {
    // @TODO ... do something
  }
}

/**
 * Get fields required by Agency
 * @return \bibdkReservationUserInput
 */
function bibdk_favourite_get_agency_fields($agencyId) {
  $agency = new TingClientAgencyBranch(NULL, $agencyId);
  $fields = $agency->getAgencyFields();
  return $fields;
}

/**
 * \brief Get favourite agencies for the user
 *
 * @global type $user
 * @return TingClientAgencyBranch
 */
function _bibdk_favourite_get_from_webservice() {
  global $user;
  if (ding_user_is_provider_user($user)) {
    try {
      $creds = ding_user_get_creds($user);
    } catch (Exception $e) {
      // do nothing
    }
    if (empty($creds)) {
      return array();
    }
// call openuserinfo webservice
    // @TODO cache
    $xml = bibdk_provider_get_favourites($creds['name']);
    module_load_include('inc', 'bibdk_favourite', 'bibdk_favourite.agencies');

    $saved_agencies = bibdk_favourite_parse_agencies($xml);

    // get the real agency(branch)
    $client = new ting_client_class();
    $agencies = array();
    foreach ($saved_agencies as $key => $agency) {
      $params = array('action' => 'findLibraryRequest', 'agencyId' => $agency['oui:agencyId']);
      // call openagency webservice to get full agencies
      // @TODO cache
      $result = $client->do_agency($params);
      if (isset($result->findLibraryResponse->pickupAgency)) {
        // there should be one and only one agency in result
        $obj = new TingClientAgencyBranch($result->findLibraryResponse->pickupAgency[0]);
        $obj->userdata = unserialize($saved_agencies[$key]['oui:userData']);
        $agencies[$agency['oui:agencyId']] = $obj;
      }
    }

    return $agencies;
  }
  // user is not ding_provider_user
  return array();
}

function bibdk_favourite_set_favourite($branchId) {
  global $user;
  if ($user->uid) {
    if (ding_user_is_provider_user($user)) {
      try {
        $creds = ding_user_get_creds($user);
      } catch (Exception $e) {
        // do nothing
      }
      // check if user is logged in and if so if user is provider user
      $response = bibdk_provider_set_favourite($creds['name'], $branchId);

      return $response;
    }
    // user is not provider user
    // @TODO; return something else
    return 'FALSE';
  }
  // user is not logged in
  // @TODO; return something else
  return 'FALSE';
}

function bibdk_favourite_get_action_links($branch) {
  // add ajax library to intrepret the use-ajax class
  drupal_add_library('system', 'drupal.ajax');

  $links = array();
  $links[] = l(t('delete_favourite'), 'favourite_delete/ajax/' . $branch->branchId, array('attributes' => array('class' => array('use-ajax', 'favourite-delete'))));
  $links[] = l(t('set_as_favourite'), 'favourite_set/ajax/' . $branch->branchId, array('attributes' => array('class' => array('use-ajax', 'favourite-set'))));
  $links[] = l(t('Edit_data'), 'overlay/favourite/userdata/' . $branch->branchId, array('attributes' => array('rel'=>array('bibdkFavorite'),'class' => array('favourite-edit', ' bibdk-popup-link'))));

  foreach ($links as $link) {
    $item['data'] = $link;
    $items[] = $item;
  }

  return theme('item_list', array('items' => $items));
}

/**
 * Implements hook_menu
 * BIG @TODO access check
 */
function bibdk_favourite_menu() {
  global $user;
  // form to edit favourite data
  $items['overlay/favourite/userdata/%'] = array(
    'title' => t('Edit_favourite_data'),
    'description' => 'Library helpdesk form.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bibdk_favourite_user_form_fields', 3),
    'access arguments' => array('access content'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // ajax call for deleting a favourite
  $items['favourite_delete/ajax/%'] = array(
    'title' => 'ajax_delete_favourite',
    'page callback' => 'bibdk_favourite_ajax_link_delete_favourite',
    'page arguments' => array(2),
    // @TODO set access
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  // ajax call for setting a favourite
  $items['favourite_set/ajax/%'] = array(
    'title' => 'ajax_set_favourite',
    'page callback' => 'bibdk_favourite_ajax_link_set_favourite',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * ajax callback for setting order agency
 */
function bibdk_favourite_ajax_link_set_favourite($branchId) {
  $response = bibdk_favourite_set_favourite($branchId);

  if (!$response) {
    $text = _bibdk_favourite_set_error_text($branchId);
    $type = 'error';
  }
  else {
    $text = _bibdk_favourite_set_favourite_text($branchId);
    $type = 'status';
  }

  $commands = array();
  $selector = '.favourite_' . $branchId;

  //clear message stack
  drupal_get_messages();
  // set message
  drupal_set_message($text, $type);
  $commands[] = ajax_command_append($selector, theme('status_messages'));
  $page = array('#type' => 'ajax', '#commands' => $commands);
  ajax_deliver($page);
}

/**
 * ajax callback for deleting a favourite library
 * */
function bibdk_favourite_ajax_link_delete_favourite($branchId) {
  $response = bibdk_favourite_delete_favourite_from_session($branchId);

  if (!$response) {
    $text = _bibdk_favourite_set_error_text($branchId);
    $type = 'error';
  }
  else {
    $text = _bibdk_favourite_set_delete_text($branchId);
    $type = 'status';
  }

  $commands = array();
  $selector = '.favourite_' . $branchId;

  // clear message stack
  drupal_get_messages();
  // set message
  drupal_set_message($text, $type);

  if ($response) {
    $commands[] = ajax_command_replace($selector, theme('status_messages'));
  }
  else {
    $commands[] = ajax_command_append($selector, theme('status_messages'));
  }

  $page = array('#type' => 'ajax', '#commands' => $commands);
  ajax_deliver($page);
}

function _bibdk_favourite_set_error_text($branchId) {
  return t('bibdk_favourite_something_went_wrong');
}

function _bibdk_favourite_set_favourite_text($branchId) {
  return t('Favourite library has been set');
}

function _bibdk_favourite_set_delete_text($branchId) {
  return t('Favourite library has been deleted');
}

/**
 * Implements hook_theme
 * @return type
 */
function bibdk_favourite_theme() {
  return array(
    'bibdk_favourite_library' => array(
      'template' => 'bibdk_favourite_library',
      'variables' => array('actions' => NULL,),
    ),
    'bibdk_favourite_opening_hours' => array(
      'variables' => array('branch' => NULL,),
    ),
    'bibdk_favourite_more_info' => array(
      'template' => 'bibdk_favourite_more_info',
      'variables' => array('branch' => NULL,),
    ),
    'bibdk_favourite_tools' => array(
      'variables' => array('branch' => NULL,),
    ),
    'bibdk_favourite_address' => array(
      'variables' => array('branch' => NULL,),
    ),
    'bibdk_favourite_contact' => array(
      'variables' => array('branch' => NULL,),
    ),
  );
}

function theme_bibdk_favourite_address($variables) {
  $branch = $variables['branch'];
  $address = $branch->getAddress();
  return $address;
}

function theme_bibdk_favourite_tools($variables) {
  $branch = $variables['branch'];
  $links = $branch->getActionLinks();
  $items = array();
  if (!empty($links)) {
    foreach ($links as $name => $link) {
      $item['data'] = l($name, $link, array());
      $items[] = $item;
    }
    return theme('item_list', array('items' => $items));
  }
}

/**
 *
 * return form action elements for favourite form
 * actions are: set_favourite (button), edit_userdata(link), delete_favourite(button)
 * */
function bibdk_favourite_form_elements($branch) {
  // set as favourite button
  $element['actions'] = array(
    'order_' . $branch->branchId => array(
      '#name' => 'order_' . $branch->branchId,
      '#type' => 'button',
      '#value' => t('select_favourite'),
      '#ajax' => array(
        'callback' => 'bibdk_favourite_ajax_set_favourite',
      ),
    ),
    'branch' => array(
      '#type' => 'hiddan',
      '#value' => $branch->branchId,
    ),
    // link to popup where user can edit agencydata
    'edit' => array('#markup' => l(t('Edit_data'), 'overlay/favourite/userdata/' . $branch->branchId, array()),),
    // delete button
    'delete' => array(
      '#name' => 'delete_' . $branch->branchId,
      '#type' => 'button',
      '#value' => t('Slet'),
      '#ajax' => array(
        'callback' => 'bibdk_favourite_ajax_delete_favourite',
      ),
    ),
  );
  return $element;
}

